// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EXamination.Core.Data;
using EXamination.Core.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace EXamination.Core.Data.Configurations
{
    public partial class StudentExamConfiguration : IEntityTypeConfiguration<StudentExam>
    {
        public void Configure(EntityTypeBuilder<StudentExam> entity)
        {
            entity.HasOne(d => d.Exam).WithMany(p => p.StudentExams)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StudentExam_Exams");

            entity.HasOne(d => d.Student).WithMany(p => p.StudentExams)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StudentExam_Students");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<StudentExam> entity);
    }
}
