// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EXamination.Core.Models;

public partial class Student:BaseEntity<int>
{
    

    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; } = null!;

    public int? Age { get; set; }

    [InverseProperty("Student")]
    public virtual ICollection<StudentExam> StudentExams { get; set; } = new List<StudentExam>();
}