// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EXamination.Core.Models;

[PrimaryKey("StudentId", "ExamId")]
[Table("StudentExam")]
public partial class StudentExam
{
    [Key]
    [Column("StudentID")]
    public int StudentId { get; set; }

    [Key]
    [Column("ExamID")]
    public int ExamId { get; set; }

    [ForeignKey("ExamId")]
    [InverseProperty("StudentExams")]
    public virtual Exam Exam { get; set; } = null!;

    [ForeignKey("StudentId")]
    [InverseProperty("StudentExams")]
    public virtual Student Student { get; set; } = null!;
}